GOOGLE_SERVICE_ACCOUNT_JSON = """
{
  "type": "service_account",
  "project_id": "green-gasket-462517-u4",
  "private_key_id": "ab6312043d63b16740108eb18d4d7d7142bd470e",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCuV+akhzrMx5K2\\ndiP9y8zipLaVO4IYZ3MMcicRanqf6foR603RZ2WB5ygFiTIpHrK1RgU+GQ4BbhvI\\n...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "tnbcs-780@green-gasket-462517-u4.iam.gserviceaccount.com",
  "client_id": "114063787600301832132",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/tnbcs-780%40green-gasket-462517-u4.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
